/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapComboEts2155RouteImport } from './routes/map-combo/ets2-155'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapComboEts2155Route = MapComboEts2155RouteImport.update({
  id: '/map-combo/ets2-155',
  path: '/map-combo/ets2-155',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map-combo/ets2-155': typeof MapComboEts2155Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map-combo/ets2-155': typeof MapComboEts2155Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map-combo/ets2-155': typeof MapComboEts2155Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/map-combo/ets2-155'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/map-combo/ets2-155'
  id: '__root__' | '/' | '/map-combo/ets2-155'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapComboEts2155Route: typeof MapComboEts2155Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-combo/ets2-155': {
      id: '/map-combo/ets2-155'
      path: '/map-combo/ets2-155'
      fullPath: '/map-combo/ets2-155'
      preLoaderRoute: typeof MapComboEts2155RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapComboEts2155Route: MapComboEts2155Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
