/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapComboRouteImport } from './routes/map-combo'
import { Route as IndexRouteImport } from './routes/index'

const MapComboRoute = MapComboRouteImport.update({
  id: '/map-combo',
  path: '/map-combo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map-combo': typeof MapComboRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map-combo': typeof MapComboRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map-combo': typeof MapComboRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/map-combo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/map-combo'
  id: '__root__' | '/' | '/map-combo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapComboRoute: typeof MapComboRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map-combo': {
      id: '/map-combo'
      path: '/map-combo'
      fullPath: '/map-combo'
      preLoaderRoute: typeof MapComboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapComboRoute: MapComboRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
